---
title: "ms_2"
author: "Grace Pan"
date: "2/12/2020"
output: html_document
---

## Project 1: Shivani Aggarwal- How Couples Meet

Description: This project visualizes the ways in which different kinds of U.S. couples meet and enter into relationships.

Pro:

1) Aggarwal examines couple characteristics along a number of different variables, including earnings, age, educational attainment, and political affiliation. This helps the viewer gain a holistic picture of the couples in her sample. 
2) The chart for "Do People Tend to Partner with Those of a Similar Political Affiliation?" was particularly interesting. I am unfamiliar with this type of chart, in which there are two concrete variables and the values are marked by saturation of color, but I found it effective in communicating the way in which couples with similar political ideologies tend to get together. 


Con:

1) In "What Are The Most Common Ways In Which Couples Meet?", some of the meeting type options in the x-axis did not seem to be mutually exclusive, which skews the results. For example, I was unclear how the options "met online" and "internet site" differed. 
2) The spacing of"Frequency of Meeting Types as a Function of Respondent's Age" are too cramped, making some of the values hard to read. However, the idea of faceting my meeting types and tracking by age was a great idea. 


## Project 2: Mitsue Guerrero- Water Stress in Mexico City

Description: Given the large population and limited water resources available in Mexico City, this project visualizes the consumption at block level to identify the biggest consumers and observe the water inequality gap that is making the city run out of water by 2050.

Pro:

1) This project tackles an important question: what are the biggest factors causing Mexico City to use water at an unsustainable rate? 
2) It uses comprehensive and reliable data from the local government of Mexico City. 
3) Examining geography at the block level allows us to diagnose the problem in a targeted way. 

Con: 

1) Although the name of the website is "Who is causing water stress in Mexico City?" the website never answers the questions. It would be preferable if Guerrero were able to explicitly draw implications from her map. 
2) Relatedly, as you hover over the map, the map does not specify the name of each location. 
3) The video tutorial of the website has many unnecessary cursor movements that distract the viewer from exploring the website. 
